export default[
    {
        title: "Letchworth State Park",
        tags:["Hiking", "nature trail", "camping", "swimming", "rafting", "hot air balloon"],
        difficulty:"Easy",
        description:"Letchworth State Park, the 'Grand Canyon of the East,' is where a 17-mile stretch of the Genesee River roars through the park's scenic gorge with three major waterfalls and cliffs as high as 600 feet, surrounded by lush forests. Recently named Best State Park in the nation, Letchworth's new Humphrey Nature Center is a must-see. ",
        distance:"17.0 mi",
        imgUrl:"../assets/c3.png",
        location: "Letchworth State Park",
        rating:"4.5",
        link:"/Letchworth",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Cascade National Park",
        tags:["Hiking", "camping","mountain biking", "fishing", "wildlife watching", "photography"],
        difficulty:"Medium",
        description:"Discover the wonders of Cascade National Park, nestled in the heart of the Rocky Mountains. With its pristine alpine lakes, jagged peaks, and lush forests, Cascade offers unparalleled opportunities for outdoor adventure. Explore over 200 miles of hiking trails, ranging from easy strolls to challenging summit ascents. Camp beneath the stars at one of our rustic campgrounds or enjoy the comforts of a cozy cabin rental. ",
        distance:"11.0 mi",
        imgUrl:"/assets/c5.png",
        location: "North Cascade trail road",
        rating:"4.7",
        link:"/Cascade",
        challenges:["Summit Mount Thunder, the park's highest peak, with a guided hiking tour","Go rock climbing on the rugged cliffs of Granite Ridge.","Take a thrilling whitewater rafting trip down Rapids River","Mountain bike the challenging Switchback Trail for epic downhill thrills","Set up camp at Spruce Meadows Campground"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Evergreen Valley State Park",
        tags:["Hiking", "camping", "fishing", "wildlife viewing", "stargazing", "photography"],
        difficulty:"Novice",
        description:"Escape to the tranquility of Evergreen Valley State Park, a pristine wilderness tucked away in the heart of the Pacific Northwest. This enchanting park boasts dense forests, meandering rivers, and cascading waterfalls, offering a haven for outdoor enthusiasts.",
        distance:"5.0 mi",
        imgUrl:"/assets/c7.png",
        location: "Northeast of Santana",
        rating:"4.4",
        link:"/Evergreen",
        challenges:["Enjoy a scenic drive along Evergreen Valley Road","Picnic at Mossy Creek Picnic Area","Take a leisurely stroll along the River Bend Trail","Fish for rainbow trout at Serenity Lake","Camp under the stars"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Thunder Ridge Mountains",
        tags:["backpacking", "mountaineering", "rock climbing", "backcountry camping", "wildlife viewing"],
        difficulty:"Hard",
        description:"Immerse yourself in the rugged beauty of Thunder Ridge National Park, a wilderness oasis nestled in the heart of the Rocky Mountains. With its towering peaks, pristine alpine lakes, and vast expanses of untamed wilderness, Thunder Ridge offers a true backcountry adventure for outdoor enthusiasts.",
        distance:"25.0 mi",
        imgUrl:"/assets/c4.png",
        location: "137 Birch Hill Rd",
        rating:"4.1",
        link:"/Thunder",
        challenges:["Backpack and camp in the remote backcountry of Glacier Basin","Participate in a wilderness survival workshop with Thunder Ridge Adventure Guides.","Embark on a multi-day trek along the High Alpine Trail, navigating steep terrain and high elevations.","Test your endurance with an ultra-distance trail running race through the park's rugged landscape.","Join an extreme mountaineering expedition to conquer the technical routes of Lightning Peak."],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Sunset Ridge ",
        tags:["Hiking",  "fishing", "picnicking", "wildlife viewing", "photography"],
        difficulty:"Novice",
        description:"Welcome to Sunset Ridge State Park, a picturesque haven nestled in the rolling hills of the countryside. Known for its stunning sunsets, lush forests, and tranquil streams, Sunset Ridge offers a perfect blend of outdoor adventure and relaxation. Explore over 150 miles of well-maintained hiking trails that wind through scenic valleys.",
        distance:"2.0 mi",
        imgUrl:"/assets/c2.png",
        location: "Sunset Ridge Rd.129",
        rating:"5",
        link:"/Sunset",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Granite Ridge",
        tags:["Hiking", "nature trail", "camping", "swimming", "rafting", "hot air balloon"],
        difficulty:"Easy",
        description:"Granite Ridge National Park is an adventurer's dream come true! I spent a week exploring its challenging trails and was blown away by the stunning scenery and rugged terrain. The hiking here is tough but incredibly rewarding, with breathtaking views around every corner. Can't wait to come back and conquer more peaks!",
        distance:"6.0 mi",
        imgUrl:"/assets/c1.png",
        location: "190 Interstate Drive",
        rating:"4.5",
        link:"/Granite",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Mountain Ridge creek", 
        tags:["Hiking",  "fishing", "kayaking"],
        difficulty:"Very Hard",
        description:"A wild kayaking stream, a picturesque haven nestled in the rolling hills of the countryside. Known for its stunning sunsets, lush forests, and tranquil streams, Sunset Ridge offers a perfect blend of outdoor adventure and relaxation. Explore over 150 miles of well-maintained hiking trails that wind through scenic valleys.",
        distance:"15.0 mi",
        imgUrl:"/assets/c8.png",
        location: "Mountain Ridge road 150",
        rating:"3.8",
        link:"/Mountain",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Ever Rain Forest",
        tags:["Hiking", "nature trail", "camping", "swimming", "rafting", "hot air balloon"],
        difficulty:"Easy",
        description:"Letchworth State Park, the 'Grand Canyon of the East,' is where a 17-mile stretch of the Genesee River roars through the park's scenic gorge with three major waterfalls and cliffs as high as 600 feet, surrounded by lush forests. Recently named Best State Park in the nation, Letchworth's new Humphrey Nature Center is a must-see. ",
        distance:"8.0 mi",
        imgUrl:"/assets/c6.png",
        location: "Ever Rain Camp Route.83",
        rating:"4.9",
        link:"/Ever",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },
    {
        title: "Green Trail",
        tags:["Hiking", "nature trail", "camping", "swimming", "rafting", "hot air balloon"],
        difficulty:"Easy",
        description:"Letchworth State Park, the 'Grand Canyon of the East,' is where a 17-mile stretch of the Genesee River roars through the park's scenic gorge with three major waterfalls and cliffs as high as 600 feet, surrounded by lush forests. Recently named Best State Park in the nation, Letchworth's new Humphrey Nature Center is a must-see. ",
        distance:"3.0 mi",
        imgUrl:"/assets/c9.png",
        location: "Green Trail, John road dr.590",
        rating:"4.1",
        link:"/Green",
        challenges:["Hike the Gibsonville Trail","Rent a kayak or canoe and paddle the Genesee River","Swim at the pool near the Lower Falls","Birdwatch at the Humphrey Nature Center","Visit the William Pryor Letchworth Museum"],
        reviews:[
                {name:"Emily",star:"5",desc:"Absolutely breathtaking! The views from the overlooks are simply stunning. My family had a fantastic time picnicking near the Upper Falls. The trails were well-maintained, and we even spotted some wildlife along the way. "},
                {name:"John D. ",star:"4",desc:"Letchworth offers something for everyone. Whether you're into adventure sports like whitewater rafting or prefer a more leisurely day of birdwatching, this park has it all. "},
                {name:"Sarah R",star:"4.5",desc:"A true gem of New York State! The park's natural beauty is unmatched, with towering cliffs, cascading waterfalls, and lush forests. My friends and I had a blast kayaking down the Genesee River and exploring the gorge trails. Highly recommend for outdoor enthusiasts!"},
            ],
    },

]