export const surpriseMePrompts = [
    'A story about a lost time-traveling journal.',
    'A story about an unlikely intergalactic friendship.',
    'A story about a haunted antique shop.',
    'A story about a magical book club.',
    'panda mad scientist mixing sparkling chemicals',
    "A story about two mice in Hawaii",
    'A story about a forgotten childhood treasure map.',
    'A story about a secret society of artists',
    'A story about a mysterious circus performer',
    'A story about a cursed paintings legacy',
    'A story about a musician in a mythical realm',
    'A story about an enchanted forest guardian',
    'A story about a time loop in a small town',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
  ];